config/routes.rb
Rails.application.routes.draw do

  root 'articles#index' # Route principale

  get '/articles/:id' => 'articles#show', as: :article
  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'

  resources :users
  resources :articles, only: [:index, :show]
  resources :article, only: [:show, :edit, :update, :destroy]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


  # Cette méthode permet de récupérer tout les articles en base de donnée (méthode all)
  # et je les enregistres dans une variable @articles que je vais utiliser dans la vue index.html.erb

  # Ajout de la pagination
  def index

    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
    @articles = Article.all
  end

  # Cette méthode permet de récupérer un article en fonction de l'id passé en paramètre
  # et je l'enregistre dans une variable @article que je vais utiliser dans la vue show.html.erb
  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create
    puts params[:name]
    username = User.find_by_name(params[:session][:name])
    password =  User.find_by_password(params[:session][:password])
    if username && password
      session[:user_id] = username.id
      flash[:info] = "connecte"
      redirect_to root_url
    else
      flash[:info] = "deconnecte"
      redirect_to login_url
    end
  end

  def check

    @current_user = User.where(name: params[:name], password: params[:password]).first

    if @current_user
      session[:user_id] = @current_user.id
    else
      session[:user_id] = nil
    end
  end

  def destroy
    session[:user_id] = nil
    @current_user = nil
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url
    else
      redirect_to signup_url
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/index.html.erb
<style>
  .style_image
  {
    height: 100px;
    width: 100px;
  }
</style>

<div class="container">
  <div class="container-fluid">
    <!-- Je récupère la liste de mes articles et j'itère dessus pour afficher des <div>
    contenant mes articles -->
    <div class="row">
    <% @articles.each do |a| %>
          <% if @current_user && @current_user.role == a.role %>
              <div class="col-sm-6 col-md-3">
                <div class="thumbnail">
                  <%= image_tag a.image, :class => "style_image" %>

                  <div class="caption">
                    <h3>
                      <%= a.title %>
                    </h3>

                    <p>
                      <%= link_to "Lire l'article", article_path(a) %>
                    </p>
                  </div>
                </div>
              </div>
          <% elsif a.role == "user" %>
              <div class="col-sm-6 col-md-3">
                <div class="thumbnail">
                  <%= image_tag a.image, :class => "style_image" %>

                  <div class="caption">
                    <h3>
                      <%= a.title %>
                    </h3>

                    <p>
                      <%= link_to "Lire l'article", article_path(a) %>
                    </p>
                  </div>
                </div>
              </div>
          <% end %>
    <% end %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="container-fluid">

    <!-- Ici on affiche l'article consulté -->
        <div class="jumbotron">
          <p class="text-center">
            <%= image_tag @article.image %>
          </p>

          <h1 class="text-center">
            <%= @article.title %>
          </h1>

          <p class="text-center">
            <%= @article.content %>
          </p>

          <p class="text-right">
            <a href="/">Revenir à l'accueil</a>
          </p>

        </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>rollingbox_test</title>

  <!-- Latest compiled and minified CSS bootstrap -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Création de la navbar -->
<nav class="navbar navbar-inverse">
  <div class="container">
    <%= image_tag 'logo-epitech.jpg', :class => 'navbar-brand' %>
    <ul class="nav navbar-nav navbar-right">
    <% if @current_user %>
          <li><a><%= @current_user.name %></a></li>
          <li><%= link_to "Log out", logout_path, method: "delete" %></li>
    <% else %>
          <li><%= link_to "Log in", login_path %></a></li>
    <% end %>
      </ul>
  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/session/login.html.erb
# app/views/users/login.html.erb
<h1>Connexion</h1>
<a href="/">Retourner à l'accueil</a>
<%= form_tag "/users/login", method: :post do %>
    <div class="input-group">
      <span class="input-group-addon" id="basic-addon1">nom d'utilisateur</span>
      <input type="text" name="name" />
    </div>
    <div class="input-group">
      <span class="input-group-addon" id="basic-addon1">mot de passe</span>
      <input type="password" name="password" />
    </div>
    <input type="submit" value="Se connecter" />
<% end %>

app/views/session/new.html.erb
<div class="container">
  <%= form_for(:session, url: login_path) do |f| %>
      <div class="input-group input-group-lg">
        <span class="input-group-addon glyphicon glyphicon-user" id="basic-addon1"></span>
        <%= f.text_field :name, :placeholder => "nom d'utilisateur", :class => "form-control" %>
      </div>
      <br />
      <div class="input-group input-group-lg">
        <span class="input-group-addon glyphicon glyphicon-eye-close" id="basic-addon1"></span>
        <%= f.password_field :password, :placeholder => "mot de passe", :class => "form-control" %>
      </div>
      <br />
      <div class="form-group">
          <%= f.submit "Se connecter", :class => "btn btn-default" %>
      </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="login">
  <div class="container">
    <%= form_for :user, url: '/users' do |f| %>
        <%= f.text_field :first_name, :placeholder => 'First Name' %>
        <%= f.text_field :last_name, :placeholder => 'Last Name' %>
        <%= f.text_field :email, :placeholder => 'Email' %>
        <%= f.password_field :password, :placeholder => 'Password' %>
        <%= f.submit "Sign up", :class => "form-btn" %>
    <% end %>
  </div>
</div>